### ISSUE TITLE
InstanceExistsByProviderID should return false when nodes are removed from cloud

### ISSUE THREAD

**Issue by duyleekun** [bizflycloud/bizfly-cloud-controller-manager#17]
Following is the Kubernetes document for the method

```go
// InstanceExistsByProviderID returns true if the instance for the given provider exists.
// If false is returned with no error, the instance will be immediately deleted by the cloud controller manager.
// method should still return true for instances that exist but are stopped/sleeping.
InstanceExistsByProviderID(ctx context.Context, providerID string) (bool, error)
```

What's the reason behind `if instance is not exist, return true`? Here's the code in the question: 
https://github.com/bizflycloud/bizfly-cloud-controller-manager/blob/8f88e89c37b180b9f3ec187702d065a94a9d8cdb/cloud-controller-manager/bizfly/server.go#L157

**Comment by pmint93** [comment]
Thanks @duyleekun for reporting, the issue is addressed at PR #19
